Select * from customer limit 20;


-- Q1. What is the total revenue generated by male vs. female customers?
Select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--This analysis shows the total revenue generated by male and female customers.
It helps businesses understand which gender contributes more to sales and supports better marketing and customer targeting decisions.



-- Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount >=(Select AVG(purchase_amount) from customer)

--This analysis identifies customers who used discounts but still spent more than the average purchase amount.
It helps businesses find high-value customers and evaluate whether discounts are attracting profitable buyers.



-- Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average product rating"
from customer
group by item_purchased
Order by avg(review_rating) desc
limit 5;

--This analysis finds the top 5 products with the highest average customer review ratings.
It helps businesses identify the most liked products and improve product promotion and inventory decisions.



-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Select shipping_type, ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
Group by shipping_type

--This analysis compares the average purchase amount between Standard and Express shipping methods.
It helps businesses understand whether shipping type influences customer spending behavior.



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status,
Count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
Group by subscription_status
Order by total_revenue,avg_spend desc

--This analysis compares spending behavior between subscribed and non-subscribed customers.
It helps businesses measure the value of subscriptions by analyzing customer spending and total revenue contribution.



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;



-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
Select customer_id,previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

Select customer_segment,
COUNT(*) as "Number of Customers"
from customer_type
Group by customer_segment



-- Q8. What are the top 3 most purchased products within each category?
with item_counts as(
Select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

Select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3;



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status



-- Q10. What is the revenue contribution of each age group?
Select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




